chore: Make components.js work with new module
Unfortunately, it does not work.
2021-07-02T06:13:41.761Z [Components.js] error: Detected fatal error. Generated 'componentsjs-error-state.json' with more information.
Error: could not instantiate server from ~/solid/css-demo-module/config/default.json
Error: Cannot find module 'css-demo-module'
Require stack: